---
title: "child_deg_dashboard"
format: html
editor: visual
---




## Row 
```{r}
#| echo: false

fc_by_fc_1 <- fc_by_fc_ploter(lst = lst,plot_i = 1,
                              log2_FC_tresh_x =log2_FC_tresh_x_standard,
                              power_tresh = power_tresh_standard)
fc_by_fc_mock <- fc_by_fc_ploter(lst = lst,plot_i = 2,
                              log2_FC_tresh_x =log2_FC_tresh_x_standard,
                              power_tresh = power_tresh_standard)
fc_by_fc_3 <- fc_by_fc_ploter(lst = lst,plot_i = 3,
                              log2_FC_tresh_x =log2_FC_tresh_x_standard,
                              power_tresh = power_tresh_standard)
fc_by_fc_4 <- fc_by_fc_ploter(lst = lst,plot_i = 4,
                              log2_FC_tresh_x =log2_FC_tresh_x_standard,
                              power_tresh = power_tresh_standard)
fc_by_fc_5 <- fc_by_fc_ploter(lst = lst,plot_i = 5,
                              log2_FC_tresh_x =log2_FC_tresh_x_standard,
                              power_tresh = power_tresh_standard)
```

#### Column {width=12%}
```{r}
#| fig-width: 3
#| fig-height: 6
vulc <- vulcano_x(lst = lst,i = 2,power_tresh = power_tresh_standard,log2_FC_tresh_x = log2_FC_tresh_x_standard)
(plot_spacer())/(vulc+coord_flip()+scale_y_reverse()+ggtitle("Mock Ms4a3 pos vs. neg."))+ 
  plot_layout(heights =  c(1, 3))
```
#### Column {width=22%}
```{r}
#| title: A
#| fig-width: 5.5
#| fig-height: 6

vulc <- vulcano_x(lst = lst,i = 1,power_tresh = power_tresh_standard,log2_FC_tresh_x = log2_FC_tresh_x_standard)

vulc/ fc_by_fc_1+ 
  plot_layout(heights =  c(1, 3))
```

#### Column {width=22%}
```{r}
#| title: B
#| fig-width: 5.5
#| fig-height: 6
vulc <- vulcano_x(lst = lst,i = 3,power_tresh = power_tresh_standard,log2_FC_tresh_x = log2_FC_tresh_x_standard)
vulc/ fc_by_fc_3+ 
  plot_layout(heights =  c(1, 3))
```

#### Column {width=22%}
```{r}
#| title: C
#| fig-width: 5.5
#| fig-height: 6

vulc <- vulcano_x(lst = lst,i = 4,power_tresh = power_tresh_standard,log2_FC_tresh_x = log2_FC_tresh_x_standard)
vulc/ fc_by_fc_4+ 
  plot_layout(heights =  c(1, 3))
```

#### Column {width=22%}
```{r}
#| title: D
#| fig-width: 5.5
#| fig-height: 6
vulc <- vulcano_x(lst = lst,i = 5,power_tresh = power_tresh_standard,log2_FC_tresh_x = log2_FC_tresh_x_standard)
vulc/ fc_by_fc_5+ 
  plot_layout(heights =  c(1, 3))
```
## Row 
### Column
```{r}
#| title: shared DEG Ms4a3 pos. vs neg.
venn_dat <- list(
  A = (fc_by_fc_1[[1]] |> filter(highlight_genes=="highlight") |> pull(gene)), 
  B = (fc_by_fc_3[[1]] |> filter(highlight_genes=="highlight") |> pull(gene)), 
  C = (fc_by_fc_4[[1]] |> filter(highlight_genes=="highlight") |> pull(gene)),
  D = (fc_by_fc_5[[1]] |> filter(highlight_genes=="highlight") |> pull(gene)))
  
venn1 <- ggVennDiagram(venn_dat, label_alpha = 0)
venn1


```

### Column
```{r}
#| fig-width: 10
#| fig-height: 6
#| title: Fold changes intragroup - Ms4a3 pos. vs neg.
overlap <- calculate.overlap(venn_dat)

genes_highlighted_tbl <- fc_by_fc_1[[1]] |> filter(highlight_genes=="highlight") |> 
        bind_rows(fc_by_fc_3[[1]] |> filter(highlight_genes=="highlight")
                  ) |> 
        bind_rows(fc_by_fc_mock[[1]] |> filter(highlight_genes=="highlight")
                  )
        bind_rows(fc_by_fc_4[[1]] |> filter(highlight_genes=="highlight")
                  ) |> 
        bind_rows(fc_by_fc_5[[1]] |> filter(highlight_genes=="highlight")
                  ) 



genes_highlighted <- genes_highlighted_tbl|> pull(gene)

colnames(genes_highlighted_tbl) <- str_remove_all(colnames(genes_highlighted_tbl),".x")

dat <- markers_roc |> 
        full_join(genes_highlighted_tbl) |> 
        filter(gene %in% genes_highlighted) |> 
         arrange(factor(gene, levels = (list_c(overlap))))


dat|> ggplot(aes(gene,comparison, size=power, fill=avg_log2FC, color=highlight_genes))+
        geom_point(shape=21, stroke=2)+
        theme_minimal()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+scale_fill_viridis_b()

#+ scale_colour_manual(c("#E69F00", "#56B4E9"))
        

```



